In [11]:
include("../src/TensorDecomposition.jl")
using LinearAlgebra, LinearSolve

## Visualizing $\mathbf{A}$

In [12]:
n = 5
c = 2
r = Int(-0.5*(c+1)*(c-2*(n+1)))

D, Drev = TensorDecomposition.makeDicts(n, 4);
Binds = collect(1:r)
B, BD = TensorDecomposition.basisFn(Binds, Drev);

Y = TensorDecomposition.varTups(B, n, 4)
E, _ = TensorDecomposition.linEqTups(BD, n, 4);

In [13]:
B

15-element Vector{Vector{Int64}}:
 [0, 0, 0, 0, 0]
 [1, 0, 0, 0, 0]
 [0, 1, 0, 0, 0]
 [0, 0, 1, 0, 0]
 [0, 0, 0, 1, 0]
 [0, 0, 0, 0, 1]
 [2, 0, 0, 0, 0]
 [1, 1, 0, 0, 0]
 [1, 0, 1, 0, 0]
 [1, 0, 0, 1, 0]
 [1, 0, 0, 0, 1]
 [0, 2, 0, 0, 0]
 [0, 1, 1, 0, 0]
 [0, 1, 0, 1, 0]
 [0, 1, 0, 0, 1]

We have $n=5, c=2$, so $r=15$.  We take
$$B=\{1, x_1, x_2, x_3, x_4, x_5, x_1^2, x_1x_2, x_1x_3, x_1x_4, x_1x_5, x_2^2, x_2x_3, x_2x_4, x_2x_5\}.$$
Then $|Y|=75$, $|E|=78$.

In [14]:
E

78-element Vector{Any}:
 ([3, 0, 0, 0, 0], [0, 0, 2, 0, 0])
 ([3, 0, 0, 0, 0], [0, 0, 1, 1, 0])
 ([3, 0, 0, 0, 0], [0, 0, 1, 0, 1])
 ([3, 0, 0, 0, 0], [0, 0, 0, 2, 0])
 ([3, 0, 0, 0, 0], [0, 0, 0, 1, 1])
 ([3, 0, 0, 0, 0], [0, 0, 0, 0, 2])
 ([2, 1, 0, 0, 0], [0, 0, 2, 0, 0])
 ([2, 1, 0, 0, 0], [0, 0, 1, 1, 0])
 ([2, 1, 0, 0, 0], [0, 0, 1, 0, 1])
 ([2, 1, 0, 0, 0], [0, 0, 0, 2, 0])
 ⋮
 ([0, 2, 0, 1, 0], [0, 0, 0, 2, 0])
 ([0, 2, 0, 1, 0], [0, 0, 0, 1, 1])
 ([0, 2, 0, 1, 0], [0, 0, 0, 0, 2])
 ([0, 2, 0, 0, 1], [0, 0, 2, 0, 0])
 ([0, 2, 0, 0, 1], [0, 0, 1, 1, 0])
 ([0, 2, 0, 0, 1], [0, 0, 1, 0, 1])
 ([0, 2, 0, 0, 1], [0, 0, 0, 2, 0])
 ([0, 2, 0, 0, 1], [0, 0, 0, 1, 1])
 ([0, 2, 0, 0, 1], [0, 0, 0, 0, 2])

In [15]:
Y

75-element Vector{Any}:
 [5, 0, 0, 0, 0]
 [4, 1, 0, 0, 0]
 [4, 0, 1, 0, 0]
 [4, 0, 0, 1, 0]
 [4, 0, 0, 0, 1]
 [3, 2, 0, 0, 0]
 [3, 1, 1, 0, 0]
 [3, 1, 0, 1, 0]
 [3, 1, 0, 0, 1]
 [3, 0, 2, 0, 0]
 ⋮
 [0, 2, 2, 1, 0]
 [0, 2, 2, 0, 1]
 [0, 2, 1, 2, 0]
 [0, 2, 1, 1, 1]
 [0, 2, 1, 0, 2]
 [0, 2, 0, 3, 0]
 [0, 2, 0, 2, 1]
 [0, 2, 0, 1, 2]
 [0, 2, 0, 0, 3]

In [16]:
Z = randn(n+1, r)
T = TensorDecomposition.rankedTensor(ones(r), Z, 4; type=eltype(Z));

Tcat = TensorDecomposition.catMat(T, 2)
H0 = Tcat[Binds, Binds];

Z = Z ./ permutedims(Z[1, :])
permutedims(Z)

15×6 Matrix{Float64}:
 1.0    0.878872    -0.749469   -0.188506  -1.03325     0.0288705
 1.0   -0.123753    -0.411735    0.772538  -0.526004    1.03072
 1.0   -0.704105    -0.989699    1.09579   -0.535194   -0.107023
 1.0   -4.8924       3.30635    -0.901393  -2.4111     -1.68192
 1.0  -50.1832      -4.29775    34.6792    -2.07776   -11.4127
 1.0    0.349353    -1.11083    -2.22007   -2.86851    -2.13557
 1.0    4.23459      1.7142     -5.28862   -3.08443    -0.802018
 1.0   -0.742013    -1.28107     3.62118   -5.17777    11.07
 1.0   -1.62675     -0.0551605   0.442097  -1.14022     1.48569
 1.0   -2.12522     -0.150098    2.37091   -1.01503     2.38628
 1.0   -0.875337    -1.18129     0.794977   0.604421    0.0709665
 1.0   -0.865489    -0.349453    0.875412   0.689911   -0.112525
 1.0    3.08208      3.61928     1.90178   -1.50001    -4.14021
 1.0  -11.7195      15.6286     -7.38689   -4.65773     2.14596
 1.0   -0.00336094  -1.45677     0.908903  -0.10906    -0.472602

In [18]:
Z2 = TensorDecomposition.vandermonde(Z, 2, type=eltype(Z))
show(stdout, "text/plain", Z2)

15×21 Matrix{Float64}:
 1.0    0.878872    -0.749469   -0.188506  -1.03325     0.0288705     0.772417      -0.658688       -0.165673     -0.908097       0.0253735     0.561704       0.14128      0.774391   -0.0216375     0.0355346    0.194775     -0.00544227   1.06761    -0.0298305    0.000833505
 1.0   -0.123753    -0.411735    0.772538  -0.526004    1.03072       0.0153148      0.0509535      -0.095604      0.0650947     -0.127554      0.169526      -0.318081     0.216574   -0.424382      0.596815    -0.406358      0.796268     0.27668    -0.542161     1.06238
 1.0   -0.704105    -0.989699    1.09579   -0.535194   -0.107023      0.495764       0.696852       -0.771554      0.376833       0.0753552     0.979504      -1.08451      0.529681    0.10592       1.20076     -0.586462     -0.117275     0.286433    0.0572779    0.0114539
 1.0   -4.8924       3.30635    -0.901393  -2.4111     -1.68192      23.9355       -16.176           4.40997      11.796          8.2286       10.932         

In [121]:
A = TensorDecomposition.linearSystemA(T, H0, Binds, BD, D, Y, E, []; type=eltype(T));
A *= det(Z2[:, basis_inds])
show(stdout, "text/plain", A)

78×75 Matrix{Float64}:
  4.50385e8  -1.56799e9   -2.35635e9  -8.72612e9   -5.73142e9   7.26394e8    1.78308e9   -4.6877e9     1.45786e9   -7.4911e8   -0.0         -0.0        -0.0         -0.0         -0.0        -0.0         -0.0         -0.0         -0.0         -0.0        -0.0         -0.0        -0.0         -0.0         -0.0        -0.0       -0.0       -0.0       -0.0       -0.0       -0.0       -0.0       -0.0       -0.0       -0.0       -0.0         -0.0         -0.0         -0.0         -0.0        -0.0         -0.0        -0.0         -0.0         -0.0        -0.0       -0.0       -0.0       -0.0       -0.0       -0.0       -0.0       -0.0       -0.0       -0.0       -0.0        -0.0        -0.0        -0.0        -0.0        -0.0        -0.0        -0.0        -0.0        -0.0        -0.0       -0.0       -0.0       -0.0       -0.0       -0.0       -0.0       -0.0       -0.0       -0.0
  5.52968e8   2.35185e9    3.95136e8   7.95534e8    8.8138e8    4.05494e8   -6.0827e8    

Consider the row $(x_1^2, x_3^2)$.

In [9]:
E[1]

([3, 0, 0, 0, 0], [0, 0, 2, 0, 0])

In [123]:
toRemoves = [vars[1:10][i] - eqs[1][1] for i=1:10]

10-element Vector{Vector{Int64}}:
 [2, 0, 0, 0, 0]
 [1, 1, 0, 0, 0]
 [1, 0, 1, 0, 0]
 [1, 0, 0, 1, 0]
 [1, 0, 0, 0, 1]
 [0, 2, 0, 0, 0]
 [0, 1, 1, 0, 0]
 [0, 1, 0, 1, 0]
 [0, 1, 0, 0, 1]
 [0, 0, 2, 0, 0]

In [124]:
for toRemove in toRemoves
    toAdd = eqs[1][2]
    inds = vcat(setdiff(basis_inds, D[toRemove]), D[toAdd])
    if length(inds) == r
        println(det(Z2[:, inds]))
    end
end
println(det(Z2[:, basis_inds]))

-4.503854130103007e8
-1.5679899141077232e9
2.3563512369735084e9
-8.726121141185745e9
5.731424051096787e9
7.263937532249299e8
-1.7830782479452221e9
-4.687697343499923e9
-1.4578599054547322e9
-7.491099571689318e8


In [125]:
A[1, 1:10]

10-element Vector{Float64}:
  4.5038541301036805e8
 -1.5679899141070483e9
 -2.3563512369742074e9
 -8.726121141187927e9
 -5.731424051097755e9
  7.263937532253098e8
  1.7830782479449646e9
 -4.687697343501211e9
  1.4578599054544673e9
 -7.491099571689318e8

In the above, we see that the entries of the $(x_1^3, x_3^2)$ row of $\mathbf{A}$ are exactly certain minors of $\mathbf{Z}_2$, up to sign.

$\mathbf{A}$ is numerically full column rank.

In [127]:
A_ = Matrix(copy(A))
foreach(TensorDecomposition.normalize!, eachcol(A_));
foreach(TensorDecomposition.normalize!, eachrow(A_));
svdvals(A_)

75-element Vector{Float64}:
 2.3689989392905346
 2.0602120342809456
 1.9994257347534552
 1.8395209854224894
 1.7736749335889659
 1.7335301062395916
 1.666696059379542
 1.6404108389805725
 1.5912191443273407
 1.5785349970933755
 ⋮
 0.03784045129359676
 0.03079126085336253
 0.02494677624741042
 0.018276683002814192
 0.011677181399841098
 0.008406815031948487
 0.005277467938247258
 0.0033418496364728367
 0.0013642389210841174

## Specialization for $c=1$

In [100]:
n = 4
c = 1
r = Int(-0.5*(c+1)*(c-2*(n+1)))

D, Drev = TensorDecomposition.makeDicts(n, 4);
Binds = collect(1:r)
B, BD = TensorDecomposition.basisFn(Binds, Drev);

Y = TensorDecomposition.varTups(B, n, 4)
E, _ = TensorDecomposition.linEqTups(BD, n, 4);

In [101]:
Z = zeros(Int, r, n+1)
Z[1, :] = TensorDecomposition.e(1, n+1)

for k=2:n+1 
    Z[k, :] = TensorDecomposition.e(1, n+1) + TensorDecomposition.e(k, n+1)
end

for k=n+2:(2*n+1)
    Z[k, :] = vcat(1, [-1 for _ in 1:k-(n+1)], [2 for _ in 1:2*n+1-k])
end

T = TensorDecomposition.rankedTensor(ones(r), permutedims(Z), 4; type=eltype(Z));

Tcat = TensorDecomposition.catMat(T, 2)
H0 = Tcat[Binds, Binds];

Z

9×5 Matrix{Int64}:
 1   0   0   0   0
 1   1   0   0   0
 1   0   1   0   0
 1   0   0   1   0
 1   0   0   0   1
 1  -1   2   2   2
 1  -1  -1   2   2
 1  -1  -1  -1   2
 1  -1  -1  -1  -1

Our specialization is
$$  \mathbf{z}_1=\mathbf{e}_0, \quad \mathbf{z}_k=\mathbf{e}_0+\mathbf{e}_{k-1}, k=2, \dots, n+1, \quad \mathbf{z}_k=\begin{bmatrix}
        1 \\
        -\mathbf{1}_{(k-(n+1))\times 1} \\ 
        \mathbf{2}_{(2n+1-k)\times 1}
    \end{bmatrix}, k=n+2, \dots, 2n+1 .$$

In [112]:
A = TensorDecomposition.linearSystemA(T, H0, Binds, BD, D, Y, E, []; type=eltype(T));
show(stdout, "text/plain", Int.(round.(A)))

24×20 Matrix{Int64}:
 -1   0   0   0  1   0   0   0   0   0  0  0  0  0  0  0  0  0  0  0
 -1   2  -1   0  0   1   0   0   0   0  0  0  0  0  0  0  0  0  0  0
 -1   2   0  -1  0   0   1   0   0   0  0  0  0  0  0  0  0  0  0  0
 -1   0   0   0  0   0   0   1   0   0  0  0  0  0  0  0  0  0  0  0
 -1   0   2  -1  0   0   0   0   1   0  0  0  0  0  0  0  0  0  0  0
 -1   0   0   0  0   0   0   0   0   1  0  0  0  0  0  0  0  0  0  0
  0  -1   0   0  0   0   0   0   0   0  1  0  0  0  0  0  0  0  0  0
  0  -1   0   0  2  -1   0   0   0   0  0  1  0  0  0  0  0  0  0  0
  0  -1   0   0  2   0  -1   0   0   0  0  0  1  0  0  0  0  0  0  0
  0  -1   0   0  0   0   0   0   0   0  0  0  0  1  0  0  0  0  0  0
  0  -1   0   0  0   2  -1   0   0   0  0  0  0  0  1  0  0  0  0  0
  0  -1   0   0  0   0   0   0   0   0  0  0  0  0  0  1  0  0  0  0
  0   0  -1   0  0   0   0   0   0   0  0  1  0  0  0  0  0  0  0  0
  0   0  -1   0  0   2   0  -1   0   0  0  0  0  1  0  0  0  0  0  0
  0   0  -1  

Taking the numerical SVD, $\mathbf{A}$ is numerically full column rank; we prove this in our paper.

In [114]:
svdvals(A)

20-element Vector{Float64}:
 4.685463778876402
 4.567599417536507
 3.5843279171650693
 3.50176847521105
 3.1433237938549934
 2.763096735339239
 2.543061827521964
 1.8736778601283837
 1.6488164864241912
 1.4765967167674257
 1.313703708737721
 1.2101886989500463
 1.0009215522697346
 1.0000000000000022
 1.0000000000000004
 0.9833484428942308
 0.4343156598157839
 0.40754502953701
 0.39278638367475244
 0.11629853877833374

## Dropping rank

In [16]:
n = 2
r = n+2

D, Drev = TensorDecomposition.makeDicts(n, 4);
Binds = collect(1:r)
B, BD = TensorDecomposition.basisFn(Binds, Drev);

Y = TensorDecomposition.varTups(B, n, 4)
E1, E2 = TensorDecomposition.linEqTups(BD, n, 4);

For the following $\mathbf{Z}$, $\mathbf{z}_4=(\mathbf{z}_1+\mathbf{z}_2+\mathbf{z}_3)/3$ is generic enough, and $\mathbf{A}$ is full column rank.

In [18]:
Z = [
    1 0 0 ; 
    1 1 0 ; 
    1 1 1 ; 
    1 2/3 1/3
]
T = TensorDecomposition.rankedTensor(ones(r), permutedims(Z), 4; type=eltype(Z));

Tcat = TensorDecomposition.catMat(T, 2)
H0 = Tcat[Binds, Binds];

A = TensorDecomposition.linearSystemA(T, H0, Binds, BD, D, Y, E1, E2; type=eltype(T));
A

2×2 Matrix{Float64}:
 -0.5  1.0
 -1.0  0.5

However, if $\mathbf{z}_4=(\mathbf{z}_1+\mathbf{z}_2)/2$ then $\mathbf{A}$ drops rank.

In [21]:
Z = [
    1 0 0 ; 
    1 1 0 ; 
    1 1 1 ; 
    1 1/2 0
]
T = TensorDecomposition.rankedTensor(ones(r), permutedims(Z), 4; type=eltype(Z));

Tcat = TensorDecomposition.catMat(T, 2)
H0 = Tcat[Binds, Binds];

A = TensorDecomposition.linearSystemA(T, H0, Binds, BD, D, Y, E1, E2; type=eltype(T));
A

2×2 Matrix{Float64}:
 -9.12314e-16  1.0
 -9.12314e-16  9.12314e-16