In [1]:
include("../src/TensorDecomposition.jl")
using LinearAlgebra

In [ ]:
degrees = [1, 2, 2, 3]

n = length(degrees)-1
d = sum(degrees)

D, _ = TensorDecomposition.makeDicts(n, d);
basis, _ = TensorDecomposition.monomialBasisFn(degrees, D);
vars, params = TensorDecomposition.monomialVarFn(basis, n, d, degrees);

We consider the tensor $\phi=x_0x_1^2x_2^2x_3^3$.

The parameter set $Y_P$ is size $18$ -- therefore, the space of decompositions is $18$-dimensional.

In [3]:
params

Set{Any} with 18 elements:
  [1, 1, 7]
  [2, 2, 5]
  [4, 2, 3]
  [2, 1, 6]
  [5, 2, 3]
  [1, 2, 7]
  [2, 0, 7]
  [2, 5, 2]
  [2, 2, 6]
  [2, 1, 7]
  [0, 2, 7]
  [5, 2, 2]
  [2, 2, 7]
  [1, 5, 3]
  [2, 4, 3]
  [2, 5, 3]
  [5, 1, 3]
  [1, 2, 6]

We first choose random values for $Y_P$.

In [4]:
paramVals = randn(length(params));
lhat, Zhat, solDict = TensorDecomposition.decomposeMonomial(degrees, basis, D, vars, params, paramVals);

In [5]:
permutedims(Zhat)

36×4 Matrix{ComplexF64}:
 1.0+0.0im          -0.169524+1.12502im   …   -0.704866-1.685im
 1.0-0.0im          -0.169524-1.12502im       -0.704866+1.685im
 1.0-0.0im           -1.01489-0.663283im      -0.584864-1.46457im
 1.0+0.0im           -1.01489+0.663283im      -0.584864+1.46457im
 1.0+0.0im            1.22405-0.464796im      -0.773273-1.65737im
 1.0+0.0im            1.22405+0.464796im  …   -0.773273+1.65737im
 1.0-0.0im          -0.703424-0.778973im     0.00242583-0.320872im
 1.0+0.0im          -0.703424+0.778973im     0.00242583+0.320872im
 1.0+0.0im            1.25284+0.0im            0.130471+0.0im
 1.0+0.0im           -1.55278+0.124488im       -1.10909+0.0187111im
    ⋮                                     ⋱  
 1.0+0.0im           -1.44903+0.235103im       0.154256+1.52015im
 1.0-0.0im           0.664182-0.0im            0.995309-0.0im
 1.0-1.62923e-17im    0.77538-0.887761im       0.372079-1.07142im
 1.0+1.62923e-17im    0.77538+0.887761im  …    0.372079+1.07142im
 1.0+0.0im   

In [6]:
T = TensorDecomposition.monomialTensor(degrees)
maximum(abs.(T-TensorDecomposition.rankedTensor(lhat, Zhat, d)))

2.9404699114145616e-14

Now we consider a "canonical" decomposition of $\phi$.  This corresponds to setting the variables $x_1^5x_2^2x_3^3, x_1^2x_2^5x_3^3, x_1^2x_2^2x_3^7$ equal to $1$ and the rest of the variables equal to $0$.

In [7]:
baseParam = [degrees[2:end] + (degrees[2:end][i]+1)*TensorDecomposition.e(i, n) for i=1:n]

3-element Vector{Vector{Int64}}:
 [5, 2, 3]
 [2, 5, 3]
 [2, 2, 7]

In [8]:
paramVals = vcat(ones(length(baseParam)), zeros(length(params)-length(baseParam)))
lhat, Zhat, solDict = TensorDecomposition.decomposeMonomial(degrees, basis, D, vars, vcat(baseParam, collect(setdiff(params, baseParam))), paramVals);

In [9]:
permutedims(Zhat)

36×4 Matrix{ComplexF64}:
 1.0+0.0im          -0.5-0.866025im     …          -1.0+2.88444e-15im
 1.0-0.0im          -0.5+0.866025im                -1.0-2.88444e-15im
 1.0+7.21111e-17im  -0.5-0.866025im        -5.76889e-16-1.0im
 1.0-7.21111e-17im  -0.5+0.866025im        -5.76889e-16+1.0im
 1.0+0.0im          -0.5-0.866025im        -7.99964e-15+1.0im
 1.0+0.0im          -0.5+0.866025im     …  -7.99964e-15-1.0im
 1.0+0.0im          -0.5-0.866025im                 1.0+9.95133e-15im
 1.0-0.0im          -0.5+0.866025im                 1.0-9.95133e-15im
 1.0+0.0im          -0.5-0.866025im                -1.0-9.07927e-15im
 1.0+0.0im          -0.5+0.866025im                -1.0+9.07927e-15im
    ⋮                                   ⋱  
 1.0-0.0im           1.0-0.0im                      1.0-0.0im
 1.0-0.0im           1.0-8.65333e-16im             -1.0-4.18244e-15im
 1.0+0.0im           1.0+8.65333e-16im             -1.0+4.18244e-15im
 1.0+0.0im           1.0+1.44222e-15im  …   1.50712e-14-1.0im

Notice that $\mathbf{z}_{i, 1}$ and $\mathbf{z}_{i, 2}$ range over the $3^{\text{rd}}$ roots of unity and $\mathbf{z}_{i, 3}$ ranges over the $4^{\text{th}}$ roots of unity.

In [10]:
T = TensorDecomposition.monomialTensor(degrees)
maximum(abs.(T-TensorDecomposition.rankedTensor(lhat, Zhat, d)))

1.0508957108287289e-14